### ISSUE TITLE
Workspaces overview disappears after suspend until extension / shell restarted

### ISSUE THREAD

**Issue by Rick1029** [pop-os/cosmic-workspaces#35]
**Distribution (run `cat /etc/os-release`):**
 Pop 21.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Gnome 40.4.0 X11 (have not tried Wayland)
Cosmic version 1
Cosmic workspaces version 6
Pop shell version 2

**Issue/Bug Description:**
After a suspend and subsequently resume the workspace menu disappears. You can still gesture left and get the application overview but there are no thumbnails of all your workspaces on the left-hand side anymore. Can be fixed with ALT+F2 + "r", disabling and reenabling the workspaces extension or restarting the computer until the next suspend. Screenshots below.

**Steps to reproduce (if you know):**
Suspend and resume PC.

**Expected behavior:**
Workspaces view persists.

**Other Notes:**
I am using Dash to Dock, Cosmic Dock is disabled. Happens with Nvidia and Intel graphics.

_Normal view_
![image](https://user-images.githubusercontent.com/62437512/148533947-a5f258f2-94cd-4bc4-b2da-69e03f8749a2.png)
_After suspend_
![image](https://user-images.githubusercontent.com/62437512/148534128-b5a2aa89-d373-4fea-813a-ccb1059926b0.png)

Unrelated, but with a lot of workspaces the thumbnails shrink towards the right when they could shrink towards the left and leave more space for your windows overview.

**Comment by 13r0ck** [comment]
> Unrelated, but with a lot of workspaces the thumbnails shrink towards the right when they could shrink towards the left and leave more space for your windows overview.

Fixed #23

**Comment by Rick1029** [comment]
Installed: 0.1.0-1635961632-21.10-d0b2d18
Candidate: 0.1.0-1635961632-21.10-d0b2d18

apt and settings don't mention any upgradable packages.

**Comment by helium18** [comment]
Can confirm. It happens with me as well. I'm running Pop_OS 21.10 under Wayland. 
It persists until I reload. 

```
gnome-shell-extension-cosmic-workspaces:
  Installed: 0.1.0~1635961632~21.10~d0b2d18
  Candidate: 0.1.0~1635961632~21.10~d0b2d18
  Version table:
 *** 0.1.0~1635961632~21.10~d0b2d18 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status

```

**Comment by helium18** [comment]
It goes away when I disable Dash to Panel for some reason...

**Comment by Killercv** [comment]
Today after last POP_OS update it was freezing whole laptop you couldn't use any applications. I needed to use super + a  few times to run terminal and turn off all extensions.

**Comment by 13r0ck** [comment]
@Killercv fixed by #39

**Comment by Killercv** [comment]
Ok, now after update extension is working. But still after locking/unlocking computer I need to restart extension, because interface isn't showing.

**Comment by brintal** [comment]
I still have the same issue here. I just upgraded to Pop OS 21.10 yesterday.
After disabling and enabling "Cosmic workspaces" through the Extensions app, It works again.
```─$ apt policy gnome-shell-extension-cosmic-workspaces
gnome-shell-extension-cosmic-workspaces:
  Installed: 0.1.0~1642187850~21.10~09d34c6
  Candidate: 0.1.0~1642187850~21.10~09d34c6
  Version table:
 *** 0.1.0~1642187850~21.10~09d34c6 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by 13r0ck** [comment]
Can anyone try pop-os/cosmic-workspaces#41 to see if it fixes this issue?

**Comment by brintal** [comment]
@13r0ck I have cosmic dock completely disabled... so I guess this is unrelated

**Comment by 13r0ck** [comment]
@brintal incorrect. Cosmic-workspaces has code that calls cosmic-dock code.

**Comment by Rick1029** [comment]
> Can anyone try #41 to see if it fixes this issue?

Issue is still there on Nvidia, fixes on shell restart like usual. Haven't tested on Intel though.

**Comment by 13r0ck** [comment]
@Rick1029 
Thank you!
Can you reboot, reproduce the error then paste the output of  `journalctl -b 0` here please?

**Comment by Rick1029** [comment]
Rebooted, suspended, and resumed then ran it, the output after resume is here:
https://gist.github.com/Rick1029/13f0f08a6892a2877f9cebce2e6797cc

Full output after restarting shell to fix is here:
https://gist.github.com/Rick1029/7a53072be1580b357c17a276467a2dce

**Comment by Rick1029** [comment]
Tested on Intel as well, the same issue. I'm also seeing corruption of text and UI elements after resume on Nvidia after installing #41 but that might be a coincidence, not sure.

**Comment by 13r0ck** [comment]
Thank you! 
The text corruption is a known issue related to the nvidia driver. If you have a picture, feel free to open an issue in pop-os/nvidia-graphics-drivers

**Comment by 13r0ck** [comment]
How about #45?

If that doesn't work please provide me with a step my step example of how to reproduce from a clean install of Pop!_OS

**Comment by Rick1029** [comment]
Issue is still present after install #45. I'm not sure about reproducing from a clean install since I don't have a way to do a fresh install but these are the steps I take to reproduce.

Start computer on either Intel or Nvidia graphics. Workspaces overview is usually working out of the box (Once on Nvidia I've noticed it didn't work straight after boot and needed a shell reset - doesn't seem common though)

Suspend computer either by closing the lid or suspending from the power menu.

Resume the computer and log in, check and see workspaces overview is not working. It shows your current workspace windows and a colored dot in the upper left corner according to your GTK theme. See photo (ignore the text corruption)

Resolves by restarting the shell, turning the workspaces extension off and on again, or restarting.

![image](https://user-images.githubusercontent.com/62437512/152625887-8f74fa9b-d972-48bc-a4ce-26232bc1b9ee.png)

**Comment by Senshi00** [comment]
> Issue is still present after install #45. I'm not sure about reproducing from a clean install since I don't have a way to do a fresh install but these are the steps I take to reproduce.
> 
> Start computer on either Intel or Nvidia graphics. Workspaces overview is usually working out of the box (Once on Nvidia I've noticed it didn't work straight after boot and needed a shell reset - doesn't seem common though)
> 
> Suspend computer either by closing the lid or suspending from the power menu.
> 
> Resume the computer and log in, check and see workspaces overview is not working. It shows your current workspace windows and a colored dot in the upper left corner according to your GTK theme. See photo (ignore the text corruption)
> 
> Resolves by restarting the shell, turning the workspaces extension off and on again, or restarting.
> 
> ![image](https://user-images.githubusercontent.com/62437512/152625887-8f74fa9b-d972-48bc-a4ce-26232bc1b9ee.png)

I have the same issue. Can reproduce by simply locking the screen and logging back in.

**Comment by 13r0ck** [comment]
After further research this is a gnome-shell conflict. This is not a bug of cosmic-workspaces.

Because the way extensions work in gnome-shell each extension is just overriding functions in gnome-shell at run time. If two extensions try to re-write the same gnome-shell extension it will cause a conflict. Which is what happens here with cosmic-workspaces and any dock/dash extension.
So then by the time cosmic-workspaces loads it is expecting code that is never loaded, thus the picker is allocated a negative height. Which is then displayed as a dot on the screen.

For the upcoming 22.04 release we updated our cosmic-dock extension to use the latest upstream version of ubuntu dock (which is what almost all dash to dock extensions are based on), and we ran into this bug as well. The solution was to remove the conflicting code from cosmic-dock https://github.com/pop-os/cosmic-dock/commit/b1751862fac5a7895faf21e31f32628201818bab. Your extensions will have to do something similar. if the developers of those extensions would like to, we are open to working with them.

As the limitations of gnome-shell are today it is not possible to fix this issue from within cosmic-workspaces. I apologize for any inconvenience
